CREATE TABLE IF NOT EXISTS `settings` (
    `setting_key` VARCHAR(255) NOT NULL,
    `setting_value` TEXT NULL,
    `setting_group` VARCHAR(100) NOT NULL,
    `setting_type` VARCHAR(50) NOT NULL DEFAULT 'text',
    `setting_label` VARCHAR(255) NOT NULL,
    `setting_options` TEXT NULL,
    PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO `settings` (`setting_key`, `setting_value`, `setting_group`, `setting_type`, `setting_label`, `setting_options`) VALUES 
('app_name', 'PHP Starter Kit', 'General', 'text', 'App Name', null),
('app_url', 'http://localhost:8000', 'General', 'text', 'App URL', null),
('site_description', 'A modern PHP boilerplate', 'General', 'textarea', 'Site Description', null),
('maintenance_mode', '0', 'General', 'boolean', 'Maintenance Mode', null),
('slow_request_time', '1.0', 'Performance', 'text', 'Slow Request Threshold (s)', null),
('allow_registration', '1', 'Account', 'boolean', 'Allow Registration', null),
('email_verification', '0', 'Account', 'boolean', 'Require Email Verification', null),
('allowed_ips', '', 'Account', 'textarea', 'Allowed IPs (comma separated)', null),
('force_https', '0', 'Security', 'boolean', 'Force HTTPS', null),
('password_min_length', '8', 'Security', 'integer', 'Password Min Length', null),
('login_attempts', '5', 'Security', 'integer', 'Max Login Attempts', null),
('admin_ip_whitelist', '', 'Security', 'textarea', 'Admin IP Whitelist (comma separated)', null),
('mail_driver', 'smtp', 'Email', 'text', 'Mail Driver', null),
('mail_host', 'smtp.mailtrap.io', 'Email', 'text', 'SMTP Host', null),
('mail_port', '2525', 'Email', 'integer', 'SMTP Port', null),
('mail_username', '', 'Email', 'text', 'SMTP Username', null),
('mail_password', '', 'Email', 'password', 'SMTP Password', null),
('mail_encryption', 'tls', 'Email', 'select', 'Encryption', 'tls,ssl,none'),
('mail_from_name', 'Admin', 'Email', 'text', 'From Name', null),
('mail_from_address', 'admin@example.com', 'Email', 'text', 'From Email', null),
('google_client_id', '', 'Integrations', 'text', 'Google Client ID', null),
('google_client_secret', '', 'Integrations', 'password', 'Google Client Secret', null),
('social_facebook', '', 'Social', 'text', 'Facebook URL', null),
('social_github', '', 'Social', 'text', 'GitHub URL', null),
('social_instagram', '', 'Social', 'text', 'Instagram URL', null),
('social_twitter', '', 'Social', 'text', 'Twitter URL', null),
('social_vk', '', 'Social', 'text', 'VK URL', null),
('social_youtube', '', 'Social', 'text', 'YouTube URL', null),
('default_language', 'en', 'Localization', 'select', 'Default Language', 'en,ru,uz'),
('timezone', 'UTC', 'Localization', 'text', 'Timezone', null),
('date_format', 'Y-m-d', 'Localization', 'text', 'Date Format', null),
('theme', 'light', 'Appearance', 'select', 'Theme', 'light,dark,system'),
('primary_color', '#3498db', 'Appearance', 'color', 'Primary Color', null),
('seo_title', 'PHP Starter', 'SEO', 'text', 'Default Title', null),
('seo_description', 'Default description', 'SEO', 'textarea', 'Default Description', null),
('enable_cache', '1', 'Performance', 'boolean', 'Enable Cache', null),
('max_upload_size', '2048', 'Uploads', 'integer', 'Max Upload Size (KB)', null),
('allowed_extensions', 'jpg,png,webp,gif', 'Uploads', 'text', 'Allowed Extensions', null);
